import catchError from "../utils/catchError";

const createCategory = catchError(async (req, res) => {});
const updateCategory = catchError(async (req, res) => {});
const deleteCategory = catchError(async (req, res) => {});
const getAllCategory = catchError(async (req, res) => {});
const updateCategoryOrder = catchError(async (req, res) => {});
